package kotlinx.html

public object Attributes {
    public val id: Attribute<String> = IdAttribute("id")
    public val style: Attribute<String> = StringAttribute("style")
    public val title: Attribute<String> = IdAttribute("title")
    public val href: Attribute<Link> = LinkAttribute("href")
    public val cite: Attribute<Link> = LinkAttribute("cite")
    public val rel: Attribute<String> = StringAttribute("rel")
    public val target: Attribute<String> = StringAttribute("target")
    public val mimeType: Attribute<String> = MimeAttribute("type")
    public val width: Attribute<Int> = IntAttribute("width")
    public val height: Attribute<Int> = IntAttribute("height")
    public val action: Attribute<Link> = LinkAttribute("action")
    public val enctype: Attribute<String> = StringAttribute("enctype")
    public val method: Attribute<String> = StringAttribute("method")
    public val src: Attribute<Link> = LinkAttribute("src")
    public val alt: Attribute<String> = TextAttribute("alt")
    public val autocomplete: Attribute<Boolean> = BooleanAttribute("autocomplete", "on", "off")
    public val autofocus: Attribute<Boolean> = TickerAttribute("autofocus")
    public val checked: Attribute<Boolean> = TickerAttribute("checked")
    public val disabled: Attribute<Boolean> = TickerAttribute("disabled")
    public val maxlength: Attribute<Int> = IntAttribute("maxlength")
    public val multiple: Attribute<Boolean> = TickerAttribute("multiple")
    public val inputType: Attribute<String> = StringAttribute("type")
    public val buttonType: Attribute<String> = StringAttribute("type")
    public val name: Attribute<String> = StringAttribute("name")
    public val pattern: Attribute<String> = RegexpAttribute("pattern")
    public val placeholder: Attribute<String> = TextAttribute("placeholder")
    public val readonly: Attribute<Boolean> = TickerAttribute("readonly")
    public val required: Attribute<Boolean> = TickerAttribute("required")
    public val size: Attribute<Int> = IntAttribute("size")
    public val step: Attribute<Int> = IntAttribute("step")
    public val value: Attribute<String> = StringAttribute("value")
    public val forId: Attribute<String> = IdAttribute("for")
    public val label: Attribute<String> = TextAttribute("label")
    public val selected: Attribute<Boolean> = TickerAttribute("selected")
    public val cols: Attribute<Int> = IntAttribute("cols")
    public val rows: Attribute<Int> = IntAttribute("rows")
    public val wrap: Attribute<String> = StringAttribute("wrap")
}
